### PR TITLE
Copy rustc 1.41.0 from nixpkgs and adapt for custom targets

### LINKED ISSUE #90: Build basic rustc with musl and wasm32 targets

### PR DESCRIPTION
**Pull request by nmattia**
Closes #90

### CODE REVIEW

**Comment by nomeata** [comment]
How would I use this wasm32-enabled rust?

**Comment by nmattia** [comment]
use the `cargo` from that platform and set the `--target` to `wasm32-unknown-unknown`, or whatever flavor you need! you may also need to specify the linker.

**Comment by nomeata** [comment]
Sorry, I don’t know how to tell naersk to use a specific cargo or platform, or who to pass `--target  to. This is what I do now
```
let naersk = nixpkgs.callPackage nixpkgs.sources.naersk {}; in
let foo = (naersk.buildPackage rec {
    name = "foo";
    src = ./foo
    root = ./foo;
    CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_LINKER = "${nixpkgs.llvmPackages_9.lld}/bin/lld";
    cargoBuildOptions = x : x ++ [ "--target wasm32-unknown-unknown" ];
    doCheck = false;
    release = true;
})
```
but with a custom override that adds the wasm target to `rustc`. How do I adjust this to use the `rustc` provided by the `naersk` repo?

**Comment by nmattia** [comment]
Give me a few hours, I'll finish my work day and add an example

**Comment by nomeata** [comment]
sure, no hurry :-D

**Comment by cpick** [comment]
There's now [an example](https://github.com/nix-community/naersk/tree/master/examples/static-musl) for building against musl that may be adaptable to wasm.

**Pull request merged**
